# Site settings
title: John Sterling
email: sterli13@purdue.edu
description: > # this means to ignore newlines until "baseurl:"
   Graduate Student at Purdue University. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://johnsamuelsterling.github.io" # the base hostname & protocol for your site
production_url: "https://johnsamuelsterling.github.io"
github_username: johnsamuelsterling
permalink: /blog/:year/:month/:title.html

sass:
  style: compressed

collections:
publications:
  output: false

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions
